### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by Batarian711** [kfix/MacPin#30] opened 2018-07-14 08:27 UTC
Hi. I am a graphic designer. I volunteer to design a logo for open source projects. I can design it for you to use it in the readme file. What dou you say?

**Comment by kfix** [comment] 2018-07-16 07:32
Dupe of #12 

I need a new name and concept first, then the icon. Thanks for the offer!

**Closed as completed by kfix** 2018-07-16 07:32 UTC
